# Generated by Django 5.1.7 on 2025-03-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interns", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intern",
            options={"verbose_name": "Стажёр", "verbose_name_plural": "Стажёры"},
        ),
        migrations.AlterField(
            model_name="intern",
            name="contact_info",
            field=models.TextField(verbose_name="Контактные данные"),
        ),
        migrations.AlterField(
            model_name="intern",
            name="end_date",
            field=models.DateField(verbose_name="Дата окончания"),
        ),
        migrations.AlterField(
            model_name="intern",
            name="fullname",
            field=models.CharField(max_length=255, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="intern",
            name="start_date",
            field=models.DateField(verbose_name="Дата начала"),
        ),
    ]
