# Generated by Django 5.1.7 on 2025-03-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interns", "0003_intern_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="intern",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AddField(
            model_name="intern",
            name="given_organ",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Орган выдачи"
            ),
        ),
        migrations.AddField(
            model_name="intern",
            name="inn",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="ИНН"
            ),
        ),
        migrations.AddField(
            model_name="intern",
            name="passport",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Паспортные данные"
            ),
        ),
        migrations.AddField(
            model_name="intern",
            name="position",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Должность"
            ),
        ),
        migrations.AlterField(
            model_name="intern",
            name="contact_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="Контактные данные"
            ),
        ),
        migrations.AlterField(
            model_name="intern",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="intern",
            name="fullname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ФИО"
            ),
        ),
        migrations.AlterField(
            model_name="intern",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата начала"),
        ),
    ]
