# Generated by Django 5.1.7 on 2025-03-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interns", "0004_intern_address_intern_given_organ_intern_inn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intern",
            name="application_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата подачи заявления"
            ),
        ),
    ]
