# Generated by Django 5.1.7 on 2025-03-11 08:26

import interns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interns", "0005_intern_application_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="intern",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="intern",
            name="inn",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="ИНН",
            ),
        ),
    ]
